name: Continuous integration

on:
  push:
    branches:
    - main
    - develop
    - 'backport*'
    - 'backport*/**'
  pull_request:
    branches:
    - main
    - develop
    - 'backport*'
    - 'backport*/**'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--cfg tokio_unstable"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          cache: true
      - run: cargo check --all --all-targets
      - run: cargo check --all --all-targets --no-default-features --features alternator

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          cache: true
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3.4.0
        with:
          crate: cargo-nextest
      - run: cargo nextest run
      - run: cargo nextest run --no-default-features --features alternator

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          components: rustfmt
          cache: true
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@4066006ec54a31931b9b1fddfd38f2fdf2d27143 # v1.1.2

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          components: rustfmt, clippy
          cache: true
      - run: cargo clippy -- -D warnings
      - run: RUSTFLAGS="--cfg tokio_unstable --cfg fetch_extended_version_info" cargo clippy -- -D warnings
      - run: cargo clippy --no-default-features --features alternator -- -D warnings
